language: julia
os:
    - linux
    - osx
julia:
    - 0.4
    - 0.5
    - nightly
notifications:
  email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("FixedPointNumbers")'
    - julia -e 'cd(Pkg.dir("FixedPointNumbers", "test")); include("runtests.jl")'
